[toolchain]
# But consider `const impl` feature issue, use 08-24
# details 1 : https://github.com/rust-lang/rust/issues/114808
# details 2 : https://github.com/rust-lang/rust/pull/114781
channel = "nightly-2023-08-24"
components = [ "rust-src", "rustfmt", "llvm-tools-preview" ]
targets = [
"x86_64-apple-darwin",
"x86_64-apple-ios",
"x86_64-apple-ios-macabi",
"x86_64-apple-tvos",
"x86_64-apple-watchos-sim",
"x86_64-linux-android",
"x86_64-pc-solaris",
"x86_64-pc-windows-gnu",
"x86_64-pc-windows-gnullvm",
"x86_64-pc-windows-msvc",
"x86_64-unknown-linux-gnu",
"x86_64-unknown-linux-gnux32",
"x86_64-uwp-windows-msvc",
"x86_64h-apple-darwin",
"aarch64-apple-darwin",
"aarch64-apple-ios",
"aarch64-apple-ios-macabi",
"aarch64-apple-ios-sim",
"aarch64-apple-tvos",
"aarch64-apple-watchos-sim",
"aarch64-linux-android",
"aarch64-pc-windows-gnullvm",
"aarch64-pc-windows-msvc",
"aarch64-unknown-linux-gnu",
"aarch64-uwp-windows-msvc",
"aarch64_be-unknown-linux-gnu",
"aarch64_be-unknown-linux-gnu_ilp32",
]